[book]
authors = ["hellowac"]
language = "zh-cn"
multilingual = false
src = "src"
title = "我的python笔记"

[build]
build-dir = "docs"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 1